### PR TITLE
#40 django1.8 compatibility

### PR DESCRIPTION
**Pull request by benred42**
Fixed Django 1.8 compatibility issues and updated a few tests.

### CODE REVIEW

**Comment by benred42** [comment]
Build is failing due to lack of coverall token.

**Comment by mlavin** [comment]
:sparkles: The build is passing!  :sparkles:

**Comment by benred42** [comment]
Excellent. I'll go ahead and merge it then.

**Comment by vkurup** [comment]
Nice work @benred42!

**Pull request merged**
