### PR TITLE
MenuItemManager now inherits from MPTT TreeManager

### LINKED ISSUE #54: Delete from Admin changelist fails
Attempting to delete an item from the admin's changelist fails because it uses treenav's MenuItemManager instead of MPTT's TreeManager.  Deleting from the admin's change form, however, does work.

### PR DESCRIPTION
**Pull request by benred42**
Fixes #54 .  MenuItemManager's `get_queryset` method also now replicates the ordering behavior from TreeManager's `get_queryset`

### CODE REVIEW

**Comment by mlavin** [comment]
This isn't really the same. `TreeManager.get_queryset` returns an instance of `TreeQuerySet` and this returns a `MenuUnCacheQuerySet` which will break chaining custom queryset methods. The functionality need to either be combined or we need a better way to do the cache invalidation handled by  `MenuUnCacheQuerySet`.

**Comment by mlavin** [comment]
Maybe combine these via 
```
class MenuUnCacheQuerySet(TreeQuerySet):
...

MenuItemManager = TreeManager.from_queryset(MenuUnCacheQuerySet)()
```
based on https://docs.djangoproject.com/en/1.8/topics/db/managers/#from-queryset

**Comment by benred42** [comment]
That change works.  Have not found any evidence that we need to handle cache invalidation for queryset `.delete` or `.update`, however.  At least not in treenav.  It does look like there is at least one place where MPTT uses `.update` and one or two where it uses `.delete`.

**Comment by benred42** [comment]
Coveralls appears to fail because I removed three lines that had test coverage.

**Comment by mlavin** [comment]
Weird. I like less code.

This is, however, backwards incompatible and needs to be noted that we are removing the `.tree` manager in the off and unlikely chance that someone was using it for customization in their project.

Let's start/add some release notes and :shipit:

**Pull request merged**
