### PR TITLE
Change object_id to a CharField to allow linking to UUID PKs

### PR DESCRIPTION
**Pull request by vkurup**
Addresses #31

### CODE REVIEW

**Comment by vkurup** [comment]
Hmmm... we still have only South migrations in the develop branch, so things are getting installed directly based on models.py currently. What's the best way to approach this? Create an initial migration, instruct existing users to run migrate with `--fake-initial`, and then create a second migration for this change?

@mlavin @benred42 ^

**Comment by mlavin** [comment]
South migrations need to be removed and replaced with Django migrations. `--fake-initial` is the default for Django 1.7 but Django 1.8 users will need to use this, assuming they were previously up to date with migrations.

**Comment by mlavin** [comment]
The end result will be 2 migrations, correct.

**Comment by vkurup** [comment]
got it, thanks!

**Comment by benred42** [comment]
:see_no_evil:

**Pull request merged**
